import {StyleSheet} from 'react-native';
import colors from '../../assets/themes/colors';

export default StyleSheet.create({
  wrapper: {
    padding: 20,
    backgroundColor: colors.white,
  },
  comment: {
    width: 380,
    height: 150,
    // borderTopRightRadius: 30,
    // borderBottomRightRadius: 30,
    // borderBottomLeftRadius: 50,
    // // padding: 20,
    // backgroundColor: '#f5f5f5',
    // marginVertical: 20,
  },
  footerSeparator: {
    // height: 0.5,
    marginVertical: 10,
    // marginBottom: 10,
    padding: 0.5,
    backgroundColor: colors.grey,
  },
  profileImg2: {
    width: 30,
    height: 30,
    borderRadius: 100,
    marginRight: 8,
  },
  sendInput: {
    width: 350,
    height: 50,
    // backgroundColor:colors.grey,
    borderRadius: 10,
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    marginBottom: 20,
    // padding: 10,
  },
  InputImg2:{
    width: 30,
    height: 30,
    borderRadius: 100,
    marginRight: 8,
  },
  // subHeader: {
  //   // marginTop: 50,
  //   width: 370,
  //   height: 50,
  //   borderRadius: 10,
  //   // borderColor: colors.grey,
  //   borderWidth: 1,
  //   padding: 10,
  //   alignItems: 'flex-end',
  //   position: 'absolute',
  //   left: 30,
  //   bottom: 40,
  // },
  // inputView: {
  //   height: 50,
  //   backgroundColor: '#F9FAFB',
  //   borderRadius: 10,
  //   borderColor: 'red',
  //   borderWidth: 1,
  //   // flex: 1,
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   // justifyContent: 'space-between',
  //   paddingHorizontal: 20,
  //   marginVertical: 50,
  // },
  input: {
    flex: 1,
    color: colors.white,
  },
});