//auth login,register and logout
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

// get user id
// export const GET_USER_ID_LOADING = 'GET_USER_ID_LOADING';
export const GET_USER_ID_SUCCESS = 'GET_USER_ID_SUCCESS';
// export const GET_USER_ID_FAIL = 'GET_USER_ID_FAIL';

//get all groups 
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUPS_SUCCESS = 'GROUPS_SUCCESS';
export const GROUPS_FAIL = 'GROUPS_FAIL';

//get profile
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

//get all members
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_LOADING = 'GET_MEMBERS_LOADING';
export const GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL';

//get Messages
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

//get Timeline
export const GET_TIMELINE_SUCCESS = 'GET_TIMELINE_SUCCESS';
export const GET_TIMELINE_LOADING = 'GET_TIMELINE_LOADING';
export const GET_TIMELINE_FAIL = 'GET_TIMELINE_FAIL';

//get VIDEOS
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAIL = 'GET_VIDEOS_FAIL';
export const GET_VIDEOS_LOADING = 'GET_VIDEOS_LOADING';

// get Photos
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAIL = 'GET_PHOTOS_FAIL';
export const GET_PHOTOS_LOADING = 'GET_PHOTOS_LOADING';

//get Albums
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const GET_ALBUMS_LOADING = 'GET_ALBUMS_LOADING';

// get Documents
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENTS_FAIL = 'GET_DOCUMENTS_FAIL';
export const GET_DOCUMENTS_LOADING = 'GET_DOCUMENTS_LOADING';

//like a post
export const LIKE_A_POST ='LIKE_A_POST';
//post a comment
export const COMMENT_ON_A_POST = 'COMMENT_ON_A_POST';
//get comments on post
export const GET_COMMENTS_ON_A_POST = 'GET_COMMENTS_ON_A_POST';

export const GET_ALL_COMMENTS_LOADING = 'GET_ALL_COMMENTS_LOADING';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_ERROR = 'GET_ALL_COMMENTS_ERROR';

//GET SINGLE MEMBER INFO
export const GET_MEMBER_INFO = 'GET_MEMBER_INFO';


